version: 2.1
jobs:
  query:
    docker:
      - image: debian
    environment:
      USERNAME: service
      TOKEN: d569b956-e094-4888-b828-19660e75439b
      HOSTNAME: http://4752aaf9.ngrok.io

    steps:
      - checkout
      - run: apt update
      - run: apt-get install wget -y
      - run: wget --quiet https://github.com/lensesio/lenses-go/releases/download/3.1.0/lenses-cli-linux-386.tar.gz
      - run: tar xzvf lenses-cli-linux-386.tar.gz
      - run: mv lenses-cli-linux-386 lenses-cli
      - run: ./lenses-cli --host $HOSTNAME --token $USERNAME:$TOKEN topics
      - run: ./lenses-cli --host $HOSTNAME --token service:$TOKEN query "SELECT count(*) FROM financial_tweets" --pretty

workflows:
  version: 2.1
  download_lenses_cli:
    jobs:
      - query
