version: 2.1
jobs:
  download:
    docker:
      - image: debian
    steps:
      - checkout
      - run: echo "Hello!"
      - run: uname -a

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - download
