version: 2.1
jobs:
  download:
    docker:
      - image: debian
    steps:
      - checkout
      - run: echo $CIRCLE_REPOSITORY_URL
      - run: uname -a
      - run: pwd
      - run: ls -l

workflows:
  version: 2.1
  download_lenses_cli:
    jobs:
      - download
